version: "3.8"

networks:
    cypress:
        name: cypress

services:
    website:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        networks: [cypress]
